In [1]:
import json
import pandas as pd

In [2]:
airports_df= pd.read_csv('airports.csv')
airports_df = (
    airports_df
    .drop(columns=['home_link', 'wikipedia_link', 'keywords', 'continent', 'icao_code', 'gps_code', 'local_code']) # Drops irrelevant fields
    .dropna(subset=['iata_code']) # Removes any ports without an IATA Code
)

airports_df = airports_df[airports_df['iata_code'].str.strip() != '']
airports_df = airports_df[airports_df['type'].str.contains('airport', case=False, na=False)] # Only consider airports, not helicopter ports or balloon ports
airports_df = airports_df.rename(columns={'name': 'airport'}) 

airports_df.head()

,id,ident,type,airport,latitude_deg,longitude_deg,elevation_ft,iso_country,iso_region,municipality,scheduled_service,iata_code
204,4650,03N,small_airport,Utirik Airport,11.222219,169.851429,4.0,MH,MH-UTI,Utirik Island,yes,UTK
412,6924,07FA,medium_airport,Ocean Reef Club Airport,25.325399,-80.274803,8.0,US,US-FL,Key Largo,no,OCA
635,7139,0CO2,small_airport,Crested Butte Airpark,38.851918,-106.928341,8980.0,US,US-CO,Crested Butte,no,CSE
892,7426,0NM0,small_airport,Columbus Airport,31.823898,-107.629924,4024.0,US,US-NM,Columbus,no,CUS
989,7545,0TE7,small_airport,LBJ Ranch Airport,30.251801,-98.622498,1515.0,US,US-TX,Stonewall,no,JCY

In [3]:
countries = pd.read_csv('countries.csv')
countries = countries.drop(columns = ['id', 'wikipedia_link', 'keywords', 'continent']) 
countries.head()

  code                  name
0   AD               Andorra
1   AE  United Arab Emirates
2   AF           Afghanistan
3   AG   Antigua and Barbuda
4   AI              Anguilla

In [4]:
airports_df = airports_df.merge(
    countries[['code', 'name']],
    left_on='iso_country',
    right_on='code',
    how='left'
)

airports_df = airports_df.rename(columns={'name': 'country'}) 
airports_df = airports_df.drop(columns=['code'])

airports_df.to_csv('data/airports_cleaned.csv', index=False)

airports_df.head()

,id,ident,type,airport,latitude_deg,longitude_deg,elevation_ft,iso_country,iso_region,municipality,scheduled_service,iata_code,country
0,4650,03N,small_airport,Utirik Airport,11.222219,169.851429,4.0,MH,MH-UTI,Utirik Island,yes,UTK,Marshall Islands
1,6924,07FA,medium_airport,Ocean Reef Club Airport,25.325399,-80.274803,8.0,US,US-FL,Key Largo,no,OCA,United States
2,7139,0CO2,small_airport,Crested Butte Airpark,38.851918,-106.928341,8980.0,US,US-CO,Crested Butte,no,CSE,United States
3,7426,0NM0,small_airport,Columbus Airport,31.823898,-107.629924,4024.0,US,US-NM,Columbus,no,CUS,United States
4,7545,0TE7,small_airport,LBJ Ranch Airport,30.251801,-98.622498,1515.0,US,US-TX,Stonewall,no,JCY,United States

In [5]:
# with open("T100_Domestic_Market_and_Segment_Data_1289012864022719634.geojson", "r") as f:
#     data = json.load(f)

# travelers_df = pd.json_normalize(
#     [feature["properties"] for feature in data["features"]]
# )

# travelers_df = travelers_df.drop(columns=['enplanements','freight','mail']) # Drops irrelevant fields

# travelers_df = travelers_df[
#     travelers_df['origin'].isin(airports_df['iata_code']) # Only keep records that have IATA Code in the airports dataset
# ]

# travelers_df.to_csv('data/travelers_cleaned.csv', index=False)

# travelers_df.head(10)

    OBJECTID  year origin  passengers  departures  arrivals
52        53  2024    AAF           4           2         3
53        54  2024    ABE      451490        6620      6488
54        55  2024    ABI       97461        2315      2635
55        56  2024    ABL        3863        1045      1046
56        57  2024    ABQ     2729021       30167     30040
57        58  2024    ABR       23769         981      1024
58        59  2024    ABY       30311        1276      1285
59        60  2024    ACK      152003       10927     11083
60        61  2024    ACT       57644        1175      1175
61        62  2024    ACV      133676        2413      2629